/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=WorkerBindings` (hash: 1841fad486ae27ea3cc5eb4a2d6463a2)
interface __BaseEnv_WorkerBindings {
	GEMINI_DB: D1Database;
	GEMINI_BL: string;
	GEMINI_ORIGIN: string;
	UPSTREAM_SOCKET: boolean;
	DEFAULT_MODEL: string;
	RETRY_ATTEMPTS: number;
	GEMINI_ACCOUNT_MAX_ATTEMPTS: number;
	GEMINI_ACCOUNT_REFRESH_INTERVAL_SEC: number;
	GEMINI_ACCOUNT_CAPABILITY_TTL_SEC: number;
	GEMINI_ACCOUNT_CAPABILITY_MODE: string;
	RETRY_DELAY_SEC: number;
	REQUEST_TIMEOUT_SEC: number;
	REQUEST_BODY_MAX_BYTES: number;
	LOG_REQUESTS: boolean;
	CURRENT_INPUT_FILE_ENABLED: boolean;
	CURRENT_INPUT_FILE_MIN_BYTES: number;
	GENERIC_FILE_UPLOAD_MAX_BYTES: number;
	ADMIN_KEY: string;
	API_KEYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/worker");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_BL" | "GEMINI_ORIGIN" | "UPSTREAM_SOCKET" | "DEFAULT_MODEL" | "RETRY_ATTEMPTS" | "GEMINI_ACCOUNT_MAX_ATTEMPTS" | "GEMINI_ACCOUNT_REFRESH_INTERVAL_SEC" | "GEMINI_ACCOUNT_CAPABILITY_TTL_SEC" | "GEMINI_ACCOUNT_CAPABILITY_MODE" | "RETRY_DELAY_SEC" | "REQUEST_TIMEOUT_SEC" | "REQUEST_BODY_MAX_BYTES" | "LOG_REQUESTS" | "CURRENT_INPUT_FILE_ENABLED" | "CURRENT_INPUT_FILE_MIN_BYTES" | "GENERIC_FILE_UPLOAD_MAX_BYTES" | "ADMIN_KEY" | "API_KEYS">> {}
}
